//
//  FactCheckSession.swift
//  MedicalFactChecker
//
//  Main session model tracking a fact-check workflow.
//

import Foundation
import SwiftData

/// A fact-checking session for a single medical claim.
///
/// Tracks the entire workflow from claim input through report generation,
/// including all fetched documents, scores, citations, and cost tracking.
@Model
final class FactCheckSession {
    // MARK: - Identification

    /// Unique identifier for this session.
    /// Note: @Attribute(.unique) removed for CloudKit compatibility.
    var id: UUID = UUID()
    var claim: String = ""
    var pubmedQuery: String?
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    // MARK: - Workflow State

    /// Current workflow step (stored as raw string for SwiftData compatibility).
    private var currentStepRaw: String = "idle"

    /// Current step in the fact-checking workflow.
    var currentStep: WorkflowStep {
        get { WorkflowStep(rawValue: currentStepRaw) ?? .idle }
        set { currentStepRaw = newValue.rawValue }
    }

    var errorMessage: String?

    /// Stop reason (stored as raw string for SwiftData compatibility).
    private var stopReasonRaw: String?

    /// Reason why the workflow stopped.
    var stopReason: StopReason? {
        get {
            guard let raw = stopReasonRaw else { return nil }
            return StopReason(rawValue: raw)
        }
        set { stopReasonRaw = newValue?.rawValue }
    }

    // MARK: - Search State (for batch pagination)

    /// Total results available in PubMed for this query.
    var totalPubMedResults: Int = 0

    /// Current offset for next batch fetch.
    var currentSearchOffset: Int = 0

    /// Number of batches fetched so far.
    var batchesFetched: Int = 0

    // MARK: - Search Provider State

    /// The search provider used for this session (raw value string).
    var searchProviderRaw: String?

    /// Total results from Europe PMC (when using europePMC or both).
    var totalEuropePMCResults: Int = 0

    /// Cursor mark for Europe PMC pagination (nil for first page).
    var europePMCCursorMark: String?

    /// Whether preprints were included in Europe PMC search.
    var includedPreprints: Bool = false

    // MARK: - Smart Search State

    /// Whether smart search mode has been activated.
    var smartSearchEnabled: Bool = false

    /// Alternative queries generated by smart search (JSON-encoded array).
    var alternativeQueries: String?

    /// Index of current alternative query being processed.
    var currentAlternativeQueryIndex: Int = 0

    /// PMIDs already fetched (to avoid duplicates across queries).
    var fetchedPmids: String?

    // MARK: - Progress Tracking

    var documentsFound: Int = 0
    var documentsScored: Int = 0
    var relevantDocumentsFound: Int = 0
    var citationsExtracted: Int = 0

    // MARK: - Cost Tracking

    /// Total input tokens used in this session.
    var totalInputTokens: Int = 0

    /// Total output tokens used in this session.
    var totalOutputTokens: Int = 0

    /// Estimated cost in USD for this session.
    var estimatedCostUSD: Double = 0.0

    // MARK: - Model Information

    /// The LLM model used for this session (e.g., "claude-sonnet-4-20250514").
    var modelName: String?

    /// The LLM provider used for this session (e.g., "anthropic").
    var providerName: String?

    // MARK: - Relationships

    @Relationship(deleteRule: .cascade, inverse: \Document.session)
    var documents: [Document]? = []

    @Relationship(deleteRule: .cascade, inverse: \EvidenceReport.session)
    var report: EvidenceReport?

    // MARK: - Initialization

    /// Creates a new fact-check session for the given claim.
    ///
    /// - Parameter claim: The medical claim to fact-check.
    init(claim: String) {
        self.claim = claim
    }

    // MARK: - Computed Properties

    /// The search provider used for this session.
    var searchProvider: SearchProvider? {
        get {
            guard let raw = searchProviderRaw else { return nil }
            return SearchProvider(rawValue: raw)
        }
        set {
            searchProviderRaw = newValue?.rawValue
        }
    }

    /// Check if more documents can be fetched from PubMed.
    var canFetchMoreDocuments: Bool {
        currentSearchOffset < totalPubMedResults
    }

    /// Check if more documents can be fetched from Europe PMC.
    var canFetchMoreFromEuropePMC: Bool {
        europePMCCursorMark != nil
    }

    /// Check if more documents can be fetched from any provider.
    var canFetchMoreFromAnyProvider: Bool {
        canFetchMoreDocuments || canFetchMoreFromEuropePMC
    }

    /// Check if more evidence can be gathered (either more PubMed results or smart search available).
    ///
    /// Returns true if:
    /// - More documents available in current PubMed query, OR
    /// - Smart search hasn't been tried yet (can generate alternative queries)
    var canGetMoreEvidence: Bool {
        canFetchMoreDocuments || !smartSearchEnabled
    }

    /// Number of additional PubMed results available to fetch.
    var remainingPubMedResults: Int {
        max(0, totalPubMedResults - currentSearchOffset)
    }

    /// Documents that have been scored with relevance >= threshold.
    var relevantDocuments: [Document] {
        (documents ?? []).filter { $0.isRelevant }
    }

    /// Documents that haven't been scored yet.
    var unscoredDocuments: [Document] {
        (documents ?? []).filter { $0.relevanceScore == nil }
    }

    /// Progress percentage (0-100) for the current workflow.
    var progressPercent: Double {
        guard documentsFound > 0 else { return 0 }
        let scoringProgress = Double(documentsScored) / Double(documentsFound)
        let citationProgress = relevantDocumentsFound > 0
            ? Double(citationsExtracted) / Double(relevantDocumentsFound)
            : 0

        switch currentStep {
        case .idle:
            return 0
        case .convertingQuery:
            return 5
        case .searchingPubMed:
            return 10
        case .scoringDocuments:
            return 10 + (scoringProgress * 50)
        case .awaitingUserDecision:
            return 60
        case .extractingCitations:
            return 60 + (citationProgress * 25)
        case .generatingReport:
            return 90
        case .fetchingMoreEvidence:
            return 50  // Mid-progress for additional evidence fetch
        case .completed:
            return 100
        case .failed, .budgetExceeded:
            return 0
        }
    }

    // MARK: - Methods

    /// Record token usage and update cost estimate.
    func recordUsage(inputTokens: Int, outputTokens: Int, model: String, provider: LLMProvider? = nil) {
        totalInputTokens += inputTokens
        totalOutputTokens += outputTokens
        estimatedCostUSD += CostCalculator.calculateCost(
            model: model,
            inputTokens: inputTokens,
            outputTokens: outputTokens,
            provider: provider
        )
        updatedAt = Date()
    }
}
