// BMLibrarian Lite - Biomedical Literature Research Tool
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import Foundation
import SwiftData

/// A fact-checking session for a single medical claim.
///
/// Tracks the entire workflow from claim input through report generation,
/// including all fetched documents, scores, citations, and cost tracking.
@Model
final class FactCheckSession {
    // MARK: - Identification

    /// Unique identifier for this session.
    /// Note: @Attribute(.unique) removed for CloudKit compatibility.
    var id: UUID = UUID()
    var claim: String = ""
    var pubmedQuery: String?
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    // MARK: - Workflow State

    /// Current workflow step (stored as raw string for SwiftData compatibility).
    private var currentStepRaw: String = "idle"

    /// Current step in the fact-checking workflow.
    var currentStep: WorkflowStep {
        get { WorkflowStep(rawValue: currentStepRaw) ?? .idle }
        set { currentStepRaw = newValue.rawValue }
    }

    var errorMessage: String?

    /// Stop reason (stored as raw string for SwiftData compatibility).
    private var stopReasonRaw: String?

    /// Reason why the workflow stopped.
    var stopReason: StopReason? {
        get {
            guard let raw = stopReasonRaw else { return nil }
            return StopReason(rawValue: raw)
        }
        set { stopReasonRaw = newValue?.rawValue }
    }

    // MARK: - Search State (for batch pagination)

    /// Number of batches fetched so far.
    var batchesFetched: Int = 0

    // MARK: - Search Provider State

    /// The search provider used for this session (stored as raw value).
    ///
    /// Options: "pubmed", "europepmc", "both".
    var searchProvider: String?

    /// Whether preprints are included in the search.
    var includePreprints: Bool = false

    // MARK: - PubMed Pagination State

    /// Total results available from PubMed for this query.
    var pubmedTotalResults: Int = 0

    /// Pagination offset for PubMed (offset-based pagination).
    var pubmedOffset: Int = 0

    /// Whether more results are available from PubMed.
    var pubmedHasMore: Bool = true

    // MARK: - Europe PMC Pagination State

    /// Total results available from Europe PMC for this query.
    var europePMCTotalResults: Int = 0

    /// Pagination offset for Europe PMC (offset-based pagination).
    var europePMCOffset: Int = 0

    /// Cursor for Europe PMC pagination (cursor-based API).
    var europePMCCursor: String?

    /// Whether more results are available from Europe PMC.
    var europePMCHasMore: Bool = true

    // MARK: - Smart Search State

    /// Whether smart search mode has been activated.
    var smartSearchEnabled: Bool = false

    /// Alternative queries generated by smart search (JSON-encoded array).
    var alternativeQueries: String?

    /// Index of current alternative query being processed.
    var currentAlternativeQueryIndex: Int = 0

    /// PMIDs already fetched (to avoid duplicates across queries).
    var fetchedPmids: String?

    // MARK: - Progress Tracking

    var documentsFound: Int = 0
    var documentsScored: Int = 0
    var relevantDocumentsFound: Int = 0
    var citationsExtracted: Int = 0

    // MARK: - Cost Tracking

    /// Total input tokens used in this session.
    var totalInputTokens: Int = 0

    /// Total output tokens used in this session.
    var totalOutputTokens: Int = 0

    /// Estimated cost in USD for this session.
    var estimatedCostUSD: Double = 0.0

    // MARK: - Model Information

    /// The LLM model used for this session (e.g., "claude-sonnet-4-20250514").
    var modelName: String?

    /// The LLM provider used for this session (e.g., "anthropic").
    var providerName: String?

    // MARK: - Relationships

    @Relationship(deleteRule: .cascade, inverse: \Document.session)
    var documents: [Document]? = []

    @Relationship(deleteRule: .cascade, inverse: \EvidenceReport.session)
    var report: EvidenceReport?

    // MARK: - Initialization

    /// Creates a new fact-check session for the given claim.
    ///
    /// - Parameter claim: The medical claim to fact-check.
    init(claim: String) {
        self.claim = claim
    }

    // MARK: - Computed Properties

    /// Type-safe access to the search provider enum.
    ///
    /// Returns the `SearchProvider` enum value for this session, or nil if not set.
    var searchProviderEnum: SearchProvider? {
        get {
            guard let raw = searchProvider else { return nil }
            return SearchProvider(rawValue: raw)
        }
        set {
            searchProvider = newValue?.rawValue
        }
    }

    /// Total number of unique documents fetched for this session.
    ///
    /// Computed from the documents relationship for accuracy.
    var totalFetchedDocuments: Int {
        documents?.count ?? 0
    }

    /// Check if more documents can be fetched from any active provider.
    ///
    /// Takes into account the selected search provider and its pagination state.
    /// For PubMed, uses the hasMore flag which is derived from offset vs total.
    /// For Europe PMC, uses the hasMore flag and cursor availability.
    var canFetchMoreFromAnyProvider: Bool {
        guard let provider = searchProviderEnum else {
            // Legacy fallback: check PubMed offset-based pagination
            return pubmedOffset < pubmedTotalResults
        }

        switch provider {
        case .pubmed:
            return pubmedHasMore
        case .europePMC:
            return europePMCHasMore
        case .both:
            return pubmedHasMore || europePMCHasMore
        }
    }

    /// Check if more documents can be fetched (alias for canFetchMoreFromAnyProvider).
    ///
    /// This is the primary property to check for pagination availability.
    var canFetchMoreDocuments: Bool {
        canFetchMoreFromAnyProvider
    }

    /// Check if more evidence can be gathered (either more results or smart search available).
    ///
    /// Returns true if:
    /// - More documents available from any active provider, OR
    /// - Smart search hasn't been tried yet (can generate alternative queries)
    var canGetMoreEvidence: Bool {
        canFetchMoreFromAnyProvider || !smartSearchEnabled
    }

    /// Number of additional PubMed results available to fetch.
    var remainingPubMedResults: Int {
        max(0, pubmedTotalResults - pubmedOffset)
    }

    /// Number of additional Europe PMC results available to fetch.
    ///
    /// For cursor-based pagination, returns an estimate based on batch size
    /// since exact counts aren't available until exhausted.
    var remainingEuropePMCResults: Int {
        // Europe PMC uses cursor-based pagination, so we estimate
        // Returns 0 if no more results, otherwise the difference or estimate
        guard europePMCHasMore else { return 0 }
        let remaining = europePMCTotalResults - europePMCOffset
        return remaining > 0 ? remaining : SearchOptions.SearchOptionsDefaults.defaultMaxResults
    }

    /// Estimated remaining results for the current provider.
    ///
    /// For offset-based pagination (PubMed), returns exact count.
    /// For cursor-based pagination (Europe PMC), returns an estimate
    /// since exact counts aren't available until exhausted.
    var estimatedRemainingResults: Int {
        guard let provider = searchProviderEnum else {
            // Legacy fallback for sessions without provider set
            return remainingPubMedResults
        }

        switch provider {
        case .pubmed:
            return pubmedHasMore ? remainingPubMedResults : 0
        case .europePMC:
            return remainingEuropePMCResults
        case .both:
            return (pubmedHasMore ? remainingPubMedResults : 0) + remainingEuropePMCResults
        }
    }

    /// Documents that have been scored with relevance >= threshold.
    var relevantDocuments: [Document] {
        (documents ?? []).filter { $0.isRelevant }
    }

    /// Documents that haven't been scored yet.
    var unscoredDocuments: [Document] {
        (documents ?? []).filter { $0.relevanceScore == nil }
    }

    /// Progress percentage (0-100) for the current workflow.
    var progressPercent: Double {
        guard documentsFound > 0 else { return 0 }
        let scoringProgress = Double(documentsScored) / Double(documentsFound)
        let citationProgress = relevantDocumentsFound > 0
            ? Double(citationsExtracted) / Double(relevantDocumentsFound)
            : 0

        switch currentStep {
        case .idle:
            return 0
        case .convertingQuery:
            return 5
        case .searchingPubMed:
            return 10
        case .scoringDocuments:
            return 10 + (scoringProgress * 50)
        case .awaitingUserDecision:
            return 60
        case .extractingCitations:
            return 60 + (citationProgress * 25)
        case .generatingReport:
            return 90
        case .fetchingMoreEvidence:
            return 50  // Mid-progress for additional evidence fetch
        case .completed:
            return 100
        case .failed, .budgetExceeded:
            return 0
        }
    }

    // MARK: - Methods

    /// Record token usage and update cost estimate.
    func recordUsage(inputTokens: Int, outputTokens: Int, model: String, provider: LLMProvider? = nil) {
        totalInputTokens += inputTokens
        totalOutputTokens += outputTokens
        estimatedCostUSD += CostCalculator.calculateCost(
            model: model,
            inputTokens: inputTokens,
            outputTokens: outputTokens,
            provider: provider
        )
        updatedAt = Date()
    }
}
