// BMLibrarian Lite - Biomedical Literature Research Tool
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#if os(iOS)
import SwiftUI
import UIKit

/// Paper size options for PDF export.
enum PaperSize: String, CaseIterable, Identifiable {
    case a4 = "A4"
    case letter = "US Letter"

    var id: String { rawValue }

    /// Page dimensions in points (72 points per inch).
    var size: CGSize {
        switch self {
        case .a4:
            // A4: 210 x 297 mm = 595.28 x 841.89 points
            return CGSize(width: 595.28, height: 841.89)
        case .letter:
            // US Letter: 8.5 x 11 inches = 612 x 792 points
            return CGSize(width: 612, height: 792)
        }
    }

    /// Page margins.
    var margins: UIEdgeInsets {
        UIEdgeInsets(top: 50, left: 50, bottom: 50, right: 50)
    }

    /// Printable content area.
    var contentRect: CGRect {
        CGRect(
            x: margins.left,
            y: margins.top,
            width: size.width - margins.left - margins.right,
            height: size.height - margins.top - margins.bottom
        )
    }
}

/// Layout constants for PDF report generation.
///
/// Centralises all numeric layout values to ensure consistency
/// and make global tweaks easy (mirroring macOS `MacPDFLayout`).
private enum PDFLayout {
    // MARK: - Page Geometry

    /// Page margin in points.
    static let pageMargin: CGFloat = 50

    // MARK: - Font Sizes

    /// Report title ("Medical Fact Check Report").
    static let reportTitleFontSize: CGFloat = 20
    /// Section headings (Summary, Analysis, Statistics, …).
    static let sectionHeadingFontSize: CGFloat = 16
    /// Sub-section headings (Claim, Disclaimer headline).
    static let subHeadingFontSize: CGFloat = 14
    /// Body text and statistics values.
    static let bodyFontSize: CGFloat = 11
    /// Claim text, heading-3 in markdown.
    static let claimFontSize: CGFloat = 12
    /// Document list titles.
    static let docTitleFontSize: CGFloat = 10
    /// Date line / caption text.
    static let captionFontSize: CGFloat = 10
    /// Footnotes, author lines, per-doc metadata, disclaimer body, monospace query.
    static let footnoteFontSize: CGFloat = 9
    /// Watermark / "Generated by" line.
    static let watermarkFontSize: CGFloat = 8

    // MARK: - Verdict Badge

    /// Badge label font size.
    static let badgeFontSize: CGFloat = 14
    /// Badge horizontal text padding.
    static let badgePadding: CGFloat = 12
    /// Spacing below the badge.
    static let badgeBottomSpacing: CGFloat = 10

    // MARK: - Divider

    /// Total vertical space consumed by a divider.
    static let dividerHeight: CGFloat = 10
    /// Vertical offset of the line inside the divider space.
    static let dividerOffset: CGFloat = 5
    /// Divider stroke width.
    static let dividerStrokeWidth: CGFloat = 0.5

    // MARK: - Vertical Spacing

    /// Large gap between major sections.
    static let sectionSpacing: CGFloat = 15
    /// Medium gap (inside a section, between sub-blocks).
    static let blockSpacing: CGFloat = 10
    /// Small gap (after a sub-heading, between stat lines).
    static let itemSpacing: CGFloat = 8
    /// Extra-small gap (label-to-value, inline elements).
    static let tightSpacing: CGFloat = 4
    /// Paragraph body spacing.
    static let paragraphSpacing: CGFloat = 6
    /// Tiny gap between tightly coupled lines.
    static let microSpacing: CGFloat = 2
    /// Gap between list items.
    static let listItemSpacing: CGFloat = 3
    /// Spacing before the footer / watermark.
    static let footerTopSpacing: CGFloat = 5
    /// Estimated height for a single document entry (title + author + metadata).
    static let documentEntryHeight: CGFloat = 70

    // MARK: - Markdown Rendering

    /// Spacing before heading-1 in markdown.
    static let heading1TopSpacing: CGFloat = 12
    /// Spacing before heading-2+ in markdown.
    static let heading2TopSpacing: CGFloat = 8
    /// Spacing after any markdown heading.
    static let headingBottomSpacing: CGFloat = 4
    /// Heading-1 font size in markdown.
    static let heading1FontSize: CGFloat = 16
    /// Heading-2 font size in markdown.
    static let heading2FontSize: CGFloat = 14
    /// Heading-3 font size in markdown.
    static let heading3FontSize: CGFloat = 12
}

/// Utility for exporting evidence reports as text-based PDF documents.
///
/// Uses UIKit's text rendering for searchable, lightweight PDFs.
struct PDFExporter {

    /// UserDefaults key for storing paper size preference.
    private static let paperSizeKey = "pdf_paper_size"

    /// Get the user's preferred paper size.
    static var preferredPaperSize: PaperSize {
        get {
            if let rawValue = UserDefaults.standard.string(forKey: paperSizeKey),
               let size = PaperSize(rawValue: rawValue) {
                return size
            }
            return .a4
        }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: paperSizeKey)
        }
    }

    /// Generate a text-based PDF from an evidence report.
    ///
    /// - Parameters:
    ///   - report: The evidence report to export.
    ///   - paperSize: The paper size for the PDF.
    /// - Returns: PDF data, or nil if generation failed.
    static func generatePDFWithPagination(for report: EvidenceReport, paperSize: PaperSize) -> Data? {
        let pageSize = paperSize.size
        let contentRect = paperSize.contentRect
        let pdfRenderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))

        let data = pdfRenderer.pdfData { context in
            var currentY: CGFloat = 0
            var pageStarted = false

            func startNewPageIfNeeded() {
                if !pageStarted {
                    context.beginPage()
                    currentY = paperSize.margins.top
                    pageStarted = true
                }
            }

            func ensureSpace(for height: CGFloat) {
                let maxY = pageSize.height - paperSize.margins.bottom
                if currentY + height > maxY {
                    pageStarted = false
                    startNewPageIfNeeded()
                }
            }

            // MARK: - Text Drawing Helpers

            func drawText(_ text: String, font: UIFont, color: UIColor = .black, maxWidth: CGFloat? = nil) -> CGFloat {
                startNewPageIfNeeded()

                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.lineBreakMode = .byWordWrapping

                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraphStyle
                ]

                let width = maxWidth ?? contentRect.width
                let boundingRect = text.boundingRect(
                    with: CGSize(width: width, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )

                ensureSpace(for: boundingRect.height)

                let drawRect = CGRect(
                    x: contentRect.minX,
                    y: currentY,
                    width: width,
                    height: boundingRect.height
                )

                text.draw(with: drawRect, options: [.usesLineFragmentOrigin, .usesFontLeading], attributes: attributes, context: nil)

                currentY += boundingRect.height
                return boundingRect.height
            }

            func drawCenteredText(_ text: String, font: UIFont, color: UIColor = .black) -> CGFloat {
                startNewPageIfNeeded()

                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.alignment = .center

                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraphStyle
                ]

                let boundingRect = text.boundingRect(
                    with: CGSize(width: contentRect.width, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )

                ensureSpace(for: boundingRect.height)

                let drawRect = CGRect(
                    x: contentRect.minX,
                    y: currentY,
                    width: contentRect.width,
                    height: boundingRect.height
                )

                text.draw(with: drawRect, options: [.usesLineFragmentOrigin, .usesFontLeading], attributes: attributes, context: nil)

                currentY += boundingRect.height
                return boundingRect.height
            }

            func addSpacing(_ height: CGFloat) {
                currentY += height
            }

            func drawDivider() {
                startNewPageIfNeeded()
                ensureSpace(for: PDFLayout.dividerHeight)

                let path = UIBezierPath()
                path.move(to: CGPoint(x: contentRect.minX, y: currentY + PDFLayout.dividerOffset))
                path.addLine(to: CGPoint(x: contentRect.maxX, y: currentY + PDFLayout.dividerOffset))
                UIColor.lightGray.setStroke()
                path.lineWidth = PDFLayout.dividerStrokeWidth
                path.stroke()

                currentY += PDFLayout.dividerHeight
            }

            func drawBadge(_ text: String, color: UIColor) {
                startNewPageIfNeeded()

                let font = UIFont.boldSystemFont(ofSize: PDFLayout.badgeFontSize)
                let padding: CGFloat = PDFLayout.badgePadding
                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: UIColor.white
                ]

                let textSize = text.size(withAttributes: attributes)
                let badgeWidth = textSize.width + padding * 2
                let badgeHeight = textSize.height + padding

                ensureSpace(for: badgeHeight + PDFLayout.badgeBottomSpacing)

                let badgeX = contentRect.midX - badgeWidth / 2
                let badgeRect = CGRect(x: badgeX, y: currentY, width: badgeWidth, height: badgeHeight)

                let path = UIBezierPath(roundedRect: badgeRect, cornerRadius: badgeHeight / 2)
                color.setFill()
                path.fill()

                let textRect = CGRect(
                    x: badgeX + padding,
                    y: currentY + padding / 2,
                    width: textSize.width,
                    height: textSize.height
                )
                text.draw(in: textRect, withAttributes: attributes)

                currentY += badgeHeight + PDFLayout.badgeBottomSpacing
            }

            // MARK: - Markdown Rendering Helpers

            /// Render markdown text with proper formatting for headers, bold, lists, etc.
            func drawMarkdown(_ markdown: String) {
                let normalizedText = normalizeLineBreaks(markdown)
                let blocks = parseMarkdownBlocks(normalizedText)

                for block in blocks {
                    switch block {
                    case .heading(let level, let text):
                        addSpacing(level == 1 ? PDFLayout.heading1TopSpacing : PDFLayout.heading2TopSpacing)
                        let font: UIFont = switch level {
                        case 1: .boldSystemFont(ofSize: PDFLayout.heading1FontSize)
                        case 2: .boldSystemFont(ofSize: PDFLayout.heading2FontSize)
                        default: .boldSystemFont(ofSize: PDFLayout.heading3FontSize)
                        }
                        _ = drawText(text, font: font)
                        addSpacing(PDFLayout.headingBottomSpacing)

                    case .paragraph(let text):
                        let cleanedText = convertReferencesToPlainText(text)
                        _ = drawFormattedText(cleanedText, baseFont: .systemFont(ofSize: PDFLayout.bodyFontSize))
                        addSpacing(PDFLayout.paragraphSpacing)

                    case .listItem(let text, let ordered, let number):
                        let cleanedText = convertReferencesToPlainText(text)
                        let bullet = ordered ? "\(number ?? 1)." : "•"
                        _ = drawFormattedText("\(bullet) \(cleanedText)", baseFont: .systemFont(ofSize: PDFLayout.bodyFontSize))
                        addSpacing(PDFLayout.listItemSpacing)
                    }
                }
            }

            /// Draw text with inline bold formatting preserved.
            func drawFormattedText(_ text: String, baseFont: UIFont) -> CGFloat {
                startNewPageIfNeeded()

                let attributedString = NSMutableAttributedString()
                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.lineBreakMode = .byWordWrapping

                // Parse bold markers and create attributed string
                var remaining = text
                while !remaining.isEmpty {
                    if let boldStart = remaining.range(of: "**") {
                        // Add text before bold marker
                        let beforeBold = String(remaining[..<boldStart.lowerBound])
                        if !beforeBold.isEmpty {
                            attributedString.append(NSAttributedString(
                                string: beforeBold,
                                attributes: [.font: baseFont, .paragraphStyle: paragraphStyle]
                            ))
                        }

                        // Find closing bold marker
                        let afterStart = remaining[boldStart.upperBound...]
                        if let boldEnd = afterStart.range(of: "**") {
                            let boldText = String(afterStart[..<boldEnd.lowerBound])
                            let boldFont = UIFont.boldSystemFont(ofSize: baseFont.pointSize)
                            attributedString.append(NSAttributedString(
                                string: boldText,
                                attributes: [.font: boldFont, .paragraphStyle: paragraphStyle]
                            ))
                            remaining = String(afterStart[boldEnd.upperBound...])
                        } else {
                            // No closing marker, treat as regular text
                            remaining = String(remaining[boldStart.upperBound...])
                        }
                    } else {
                        // No more bold markers
                        attributedString.append(NSAttributedString(
                            string: remaining,
                            attributes: [.font: baseFont, .paragraphStyle: paragraphStyle]
                        ))
                        remaining = ""
                    }
                }

                let boundingRect = attributedString.boundingRect(
                    with: CGSize(width: contentRect.width, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    context: nil
                )

                ensureSpace(for: boundingRect.height)

                let drawRect = CGRect(
                    x: contentRect.minX,
                    y: currentY,
                    width: contentRect.width,
                    height: boundingRect.height
                )

                attributedString.draw(with: drawRect, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)

                currentY += boundingRect.height
                return boundingRect.height
            }

            // MARK: - Render Report Content

            // Header
            startNewPageIfNeeded()
            _ = drawText("Medical Fact Check Report", font: .boldSystemFont(ofSize: PDFLayout.reportTitleFontSize))
            _ = drawText("Generated: \(report.generatedAt.formatted(date: .abbreviated, time: .shortened))",
                        font: .systemFont(ofSize: PDFLayout.captionFontSize), color: .gray)
            addSpacing(PDFLayout.sectionSpacing)

            // Verdict Badge
            let verdictColor: UIColor = switch report.verdict {
            case .supported: .systemGreen
            case .partiallySupported: .systemOrange
            case .notSupported: .systemRed
            case .insufficientEvidence: .systemGray
            case .conflicting: .systemPurple
            }
            drawBadge(report.verdict.rawValue, color: verdictColor)
            addSpacing(PDFLayout.blockSpacing)

            // Claim
            if let session = report.session {
                _ = drawText("Claim", font: .boldSystemFont(ofSize: PDFLayout.subHeadingFontSize), color: .darkGray)
                addSpacing(PDFLayout.tightSpacing)
                _ = drawText(session.claim, font: .italicSystemFont(ofSize: PDFLayout.claimFontSize))
                addSpacing(PDFLayout.itemSpacing)

                if let query = session.pubmedQuery {
                    _ = drawText("PubMed Query", font: .boldSystemFont(ofSize: PDFLayout.bodyFontSize), color: .gray)
                    addSpacing(PDFLayout.microSpacing)
                    _ = drawText(query, font: UIFont(name: "Menlo", size: PDFLayout.footnoteFontSize) ?? .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .systemBlue)
                }
                addSpacing(PDFLayout.sectionSpacing)
            }

            drawDivider()

            // Summary
            _ = drawText("Summary", font: .boldSystemFont(ofSize: PDFLayout.sectionHeadingFontSize))
            addSpacing(PDFLayout.paragraphSpacing)
            _ = drawText(report.summary, font: .systemFont(ofSize: PDFLayout.bodyFontSize))
            addSpacing(PDFLayout.sectionSpacing)

            drawDivider()

            // Detailed Report - now with proper markdown rendering
            _ = drawText("Detailed Analysis", font: .boldSystemFont(ofSize: PDFLayout.sectionHeadingFontSize))
            addSpacing(PDFLayout.itemSpacing)
            drawMarkdown(report.fullReport)
            addSpacing(PDFLayout.sectionSpacing)

            drawDivider()

            // Statistics
            _ = drawText("Statistics", font: .boldSystemFont(ofSize: PDFLayout.sectionHeadingFontSize))
            addSpacing(PDFLayout.paragraphSpacing)
            _ = drawText("Documents Reviewed: \(report.documentsReviewed)", font: .systemFont(ofSize: PDFLayout.bodyFontSize))
            _ = drawText("Relevant Sources: \(report.uniqueSourceCount)", font: .systemFont(ofSize: PDFLayout.bodyFontSize))
            _ = drawText("Citations: \(report.citationCount)", font: .systemFont(ofSize: PDFLayout.bodyFontSize))
            addSpacing(PDFLayout.sectionSpacing)

            // Reviewed Documents
            if let session = report.session {
                let relevantDocs = (session.documents ?? []).filter { ($0.relevanceScore ?? 0) >= 3 }
                    .sorted { ($0.relevanceScore ?? 0) > ($1.relevanceScore ?? 0) }

                if !relevantDocs.isEmpty {
                    drawDivider()
                    _ = drawText("Reviewed Documents", font: .boldSystemFont(ofSize: PDFLayout.sectionHeadingFontSize))
                    addSpacing(PDFLayout.itemSpacing)

                    for doc in relevantDocs {
                        ensureSpace(for: PDFLayout.documentEntryHeight)

                        _ = drawText("• \(doc.title)", font: .boldSystemFont(ofSize: PDFLayout.docTitleFontSize))
                        _ = drawText("  \(doc.formattedAuthors)", font: .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .darkGray)
                        if let journal = doc.journal, let year = doc.year {
                            _ = drawText("  \(journal), \(year) • PMID: \(doc.pmid)", font: .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .gray)
                        } else {
                            _ = drawText("  PMID: \(doc.pmid)", font: .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .gray)
                        }
                        if let score = doc.relevanceScore {
                            _ = drawText("  Relevance Score: \(score)/5", font: .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .systemBlue)
                        }
                        addSpacing(PDFLayout.itemSpacing)
                    }
                    addSpacing(PDFLayout.sectionSpacing)
                }
            }

            // Footer with disclaimer
            drawDivider()
            addSpacing(PDFLayout.footerTopSpacing)

            // Generation footnote
            _ = drawText(report.generationFootnote, font: .systemFont(ofSize: PDFLayout.footnoteFontSize), color: .gray)
            addSpacing(PDFLayout.blockSpacing)

            // Disclaimer
            _ = drawText("Important Disclaimer", font: .boldSystemFont(ofSize: PDFLayout.bodyFontSize), color: .systemOrange)
            addSpacing(PDFLayout.tightSpacing)
            _ = drawText(
                "This report is generated by AI and is intended for informational purposes only. " +
                "It should not be used for self-diagnosis or treatment. Always consult qualified " +
                "healthcare professionals for medical advice and discuss any findings from this " +
                "report with your doctor.",
                font: .systemFont(ofSize: PDFLayout.footnoteFontSize),
                color: .darkGray
            )
            addSpacing(PDFLayout.sectionSpacing)

            _ = drawText("Generated by Medical Fact Checker", font: .systemFont(ofSize: PDFLayout.watermarkFontSize), color: .lightGray)
        }

        return data
    }

    // MARK: - Markdown Parsing Types

    /// Block types for markdown parsing.
    private enum MarkdownBlock {
        case heading(level: Int, text: String)
        case paragraph(text: String)
        case listItem(text: String, ordered: Bool, number: Int?)
    }

    // MARK: - Markdown Parsing

    /// Normalize line breaks in markdown text.
    private static func normalizeLineBreaks(_ text: String) -> String {
        var result = text
        result = result.replacingOccurrences(of: "\\n", with: "\n")
        while result.contains("\n\n\n") {
            result = result.replacingOccurrences(of: "\n\n\n", with: "\n\n")
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Parse markdown text into structured blocks.
    private static func parseMarkdownBlocks(_ text: String) -> [MarkdownBlock] {
        let lines = text.components(separatedBy: "\n")
        var blocks: [MarkdownBlock] = []
        var currentParagraph: [String] = []
        var listNumber = 0

        func flushParagraph() {
            if !currentParagraph.isEmpty {
                blocks.append(.paragraph(text: currentParagraph.joined(separator: " ")))
                currentParagraph = []
            }
        }

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)

            if trimmed.isEmpty {
                flushParagraph()
                listNumber = 0
                continue
            }

            // Headers
            if trimmed.hasPrefix("### ") {
                flushParagraph()
                blocks.append(.heading(level: 3, text: String(trimmed.dropFirst(4))))
                listNumber = 0
                continue
            }
            if trimmed.hasPrefix("## ") {
                flushParagraph()
                blocks.append(.heading(level: 2, text: String(trimmed.dropFirst(3))))
                listNumber = 0
                continue
            }
            if trimmed.hasPrefix("# ") {
                flushParagraph()
                blocks.append(.heading(level: 1, text: String(trimmed.dropFirst(2))))
                listNumber = 0
                continue
            }

            // Unordered list
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                flushParagraph()
                blocks.append(.listItem(text: String(trimmed.dropFirst(2)), ordered: false, number: nil))
                listNumber = 0
                continue
            }

            // Ordered list
            if let match = parseOrderedListItem(trimmed) {
                flushParagraph()
                listNumber += 1
                blocks.append(.listItem(text: match, ordered: true, number: listNumber))
                continue
            }

            currentParagraph.append(trimmed)
        }

        flushParagraph()
        return blocks
    }

    /// Parse an ordered list item line.
    private static func parseOrderedListItem(_ line: String) -> String? {
        let pattern = "^\\d+\\.\\s+(.+)$"
        guard let regex = try? NSRegularExpression(pattern: pattern),
              let match = regex.firstMatch(in: line, range: NSRange(line.startIndex..., in: line)),
              let textRange = Range(match.range(at: 1), in: line) else {
            return nil
        }
        return String(line[textRange])
    }

    /// Convert interactive references to plain text with PMIDs.
    ///
    /// Converts `[Author, Year](doc:pmid-12345)` to `Author, Year (PMID: 12345)`.
    private static func convertReferencesToPlainText(_ text: String) -> String {
        var result = text

        // Pattern for references with document ID: [Author, Year](doc:pmid-12345)
        let patternWithId = "\\[([^\\]]+)\\]\\(doc:pmid-(\\d+)\\)"
        if let regex = try? NSRegularExpression(pattern: patternWithId) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1 (PMID: $2)"
            )
        }

        // Pattern for references with generic doc ID: [Author, Year](doc:id)
        let patternGenericId = "\\[([^\\]]+)\\]\\(doc:[^)]+\\)"
        if let regex = try? NSRegularExpression(pattern: patternGenericId) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1"
            )
        }

        // Remove remaining markdown link syntax: [text](url) -> text
        let linkPattern = "\\[([^\\]]+)\\]\\([^)]+\\)"
        if let regex = try? NSRegularExpression(pattern: linkPattern) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1"
            )
        }

        return result
    }

    /// Create a temporary file URL for the PDF.
    ///
    /// - Parameter report: The report to generate a filename for.
    /// - Returns: A temporary file URL for saving the PDF.
    static func temporaryFileURL(for report: EvidenceReport) -> URL {
        let filename = "FactCheck_\(report.generatedAt.formatted(.dateTime.year().month().day().hour().minute())).pdf"
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: ",", with: "")
            .replacingOccurrences(of: ":", with: "-")

        return FileManager.default.temporaryDirectory.appendingPathComponent(filename)
    }

    /// Save PDF data to a temporary file and return the URL.
    ///
    /// - Parameters:
    ///   - data: The PDF data to save.
    ///   - report: The report (used for filename generation).
    /// - Returns: The file URL where the PDF was saved, or nil if saving failed.
    static func savePDFToTemporaryFile(_ data: Data, for report: EvidenceReport) -> URL? {
        let url = temporaryFileURL(for: report)

        do {
            try data.write(to: url)
            return url
        } catch {
            print("[PDFExporter] Failed to save PDF: \(error.localizedDescription)")
            return nil
        }
    }
}

// MARK: - PDF Document Wrapper

/// A wrapper for PDF data that can be used with ShareLink.
struct PDFDocument: Transferable {
    let data: Data
    let filename: String

    static var transferRepresentation: some TransferRepresentation {
        DataRepresentation(exportedContentType: .pdf) { document in
            document.data
        }
        .suggestedFileName { document in
            document.filename
        }
    }
}

#endif // os(iOS)
