// BMLibrarian Lite - Biomedical Literature Research Tool
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftUI

/// A non-interactive report view designed for PDF export and printing.
///
/// This view renders the full report content without interactive elements
/// like expandable sections or clickable references. References are converted
/// to plain text with PMIDs. Designed for macOS with proper paper sizing.
struct PrintableReportView: View {
    let report: EvidenceReport
    let paperSize: PaperSize

    /// Margin around the content.
    private let margin: CGFloat = 50

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Header with app name and date
            headerSection

            Divider()

            // Verdict Badge (centered)
            HStack {
                Spacer()
                printableVerdictBadge
                Spacer()
            }

            // Claim
            if let session = report.session {
                claimSection(session)
            }

            // Summary
            summarySection

            Divider()

            // Detailed Report
            detailedReportSection

            Divider()

            // Statistics
            statisticsSection

            // Reviewed Documents (if any)
            if let session = report.session, !(session.documents ?? []).isEmpty {
                documentsSection(session.documents ?? [])
            }

            Spacer(minLength: 20)

            // Footer
            footerSection
        }
        .padding(margin)
        .frame(width: paperSize.size.width)
        .background(Color.white)
    }

    // MARK: - Header

    private var headerSection: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text("Medical Fact Check Report")
                    .font(.title2)
                    .fontWeight(.bold)
                Text("Generated by Medical Fact Checker")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text(report.generatedAt.formatted(date: .abbreviated, time: .shortened))
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
    }

    // MARK: - Verdict Badge

    private var printableVerdictBadge: some View {
        Text(report.verdict.rawValue)
            .font(.headline)
            .padding(.horizontal, 20)
            .padding(.vertical, 10)
            .background(verdictColor)
            .foregroundColor(.white)
            .cornerRadius(25)
    }

    private var verdictColor: Color {
        switch report.verdict {
        case .supported: return .green
        case .partiallySupported: return .orange
        case .notSupported: return .red
        case .insufficientEvidence: return .gray
        case .conflicting: return .purple
        }
    }

    // MARK: - Claim Section

    private func claimSection(_ session: FactCheckSession) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Claim")
                .font(.headline)
            Text(session.claim)
                .font(.body)
                .italic()

            if let query = session.pubmedQuery {
                Text("PubMed Query")
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .padding(.top, 4)
                Text(query)
                    .font(.caption)
                    .fontDesign(.monospaced)
            }
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.gray.opacity(0.1))
        .cornerRadius(8)
    }

    // MARK: - Summary Section

    private var summarySection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Summary")
                .font(.headline)
            Text(report.summary)
                .font(.body)
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.blue.opacity(0.1))
        .cornerRadius(8)
    }

    // MARK: - Detailed Report Section

    private var detailedReportSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Detailed Analysis")
                .font(.headline)

            // Render markdown as plain text, converting references
            PrintableMarkdownView(content: report.fullReport)
        }
    }

    // MARK: - Statistics Section

    private var statisticsSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Statistics")
                .font(.headline)

            HStack(spacing: 40) {
                printableStatItem(
                    label: "Documents Reviewed",
                    value: "\(report.documentsReviewed)"
                )
                printableStatItem(
                    label: "Relevant Sources",
                    value: "\(report.uniqueSourceCount)"
                )
                printableStatItem(
                    label: "Citations",
                    value: "\(report.citationCount)"
                )
            }
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.gray.opacity(0.1))
        .cornerRadius(8)
    }

    private func printableStatItem(label: String, value: String) -> some View {
        VStack(spacing: 2) {
            Text(value)
                .font(.title2)
                .fontWeight(.bold)
            Text(label)
                .font(.caption)
                .foregroundColor(.secondary)
        }
    }

    // MARK: - Documents Section

    private func documentsSection(_ documents: [Document]) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Reviewed Documents")
                .font(.headline)

            // Sort by score descending
            let sortedDocs = documents.sorted {
                ($0.relevanceScore ?? 0) > ($1.relevanceScore ?? 0)
            }

            // Only show relevant documents (score >= 3)
            let relevantDocs = sortedDocs.filter { ($0.relevanceScore ?? 0) >= 3 }

            ForEach(relevantDocs, id: \.pmid) { doc in
                printableDocumentCard(doc)
            }

            if relevantDocs.count < documents.count {
                Text("+ \(documents.count - relevantDocs.count) additional documents reviewed")
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .italic()
            }
        }
    }

    private func printableDocumentCard(_ document: Document) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(document.displayTitle)
                        .font(.subheadline)
                        .fontWeight(.medium)
                    Text(document.formattedAuthors)
                        .font(.caption)
                        .foregroundColor(.secondary)
                    if let journal = document.journal, let year = document.year {
                        Text(verbatim: "\(journal), \(year)")
                            .font(.caption2)
                            .foregroundColor(.secondary)
                    }
                }

                Spacer()

                if let score = document.relevanceScore {
                    Text("\(score)")
                        .font(.caption)
                        .fontWeight(.bold)
                        .foregroundColor(.white)
                        .frame(width: 24, height: 24)
                        .background(scoreColor(score))
                        .clipShape(Circle())
                }
            }

            Text("PMID: \(document.pmid)")
                .font(.caption2)
                .foregroundColor(.secondary)
        }
        .padding(8)
        .background(Color.gray.opacity(0.05))
        .cornerRadius(4)
    }

    private func scoreColor(_ score: Int) -> Color {
        switch score {
        case 5: return .green
        case 4: return Color(red: 0.4, green: 0.7, blue: 0.3)
        case 3: return .orange
        case 2: return Color(red: 0.9, green: 0.5, blue: 0.2)
        default: return .red
        }
    }

    // MARK: - Footer

    private var footerSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Divider()

            // Generation footnote with model/provider info
            Text(report.generationFootnote)
                .font(.caption)
                .foregroundColor(.secondary)

            // Disclaimer box
            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 4) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundColor(.orange)
                    Text("Important Disclaimer")
                        .fontWeight(.semibold)
                }
                .font(.caption)

                Text("This report is generated by AI and is intended for informational purposes only. It should not be used for self-diagnosis or treatment. Always consult qualified healthcare professionals for medical advice and discuss any findings from this report with your doctor.")
                    .font(.caption2)
                    .foregroundColor(.secondary)
            }
            .padding(8)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.orange.opacity(0.1))
            .cornerRadius(6)

            // App branding
            HStack {
                Text("Generated by Medical Fact Checker")
                    .font(.caption2)
                    .foregroundColor(.secondary)
                Spacer()
            }
        }
    }
}

// MARK: - Printable Markdown View

/// Renders markdown as plain text suitable for PDF export.
///
/// Converts interactive reference links to plain text with PMIDs.
struct PrintableMarkdownView: View {
    let content: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            let blocks = parseMarkdownBlocks(normalizeLineBreaks(content))
            ForEach(Array(blocks.enumerated()), id: \.offset) { _, block in
                renderBlock(block)
            }
        }
    }

    // MARK: - Block Types

    private enum MarkdownBlock {
        case heading(level: Int, text: String)
        case paragraph(text: String)
        case listItem(text: String, ordered: Bool, number: Int?)
    }

    // MARK: - Parsing

    private func parseMarkdownBlocks(_ text: String) -> [MarkdownBlock] {
        let lines = text.components(separatedBy: "\n")
        var blocks: [MarkdownBlock] = []
        var currentParagraph: [String] = []
        var listNumber = 0

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)

            if trimmed.isEmpty {
                if !currentParagraph.isEmpty {
                    blocks.append(.paragraph(text: currentParagraph.joined(separator: " ")))
                    currentParagraph = []
                }
                listNumber = 0
                continue
            }

            // Headers
            if trimmed.hasPrefix("### ") {
                flushParagraph(&blocks, &currentParagraph)
                blocks.append(.heading(level: 3, text: String(trimmed.dropFirst(4))))
                listNumber = 0
                continue
            }
            if trimmed.hasPrefix("## ") {
                flushParagraph(&blocks, &currentParagraph)
                blocks.append(.heading(level: 2, text: String(trimmed.dropFirst(3))))
                listNumber = 0
                continue
            }
            if trimmed.hasPrefix("# ") {
                flushParagraph(&blocks, &currentParagraph)
                blocks.append(.heading(level: 1, text: String(trimmed.dropFirst(2))))
                listNumber = 0
                continue
            }

            // Unordered list
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                flushParagraph(&blocks, &currentParagraph)
                blocks.append(.listItem(text: String(trimmed.dropFirst(2)), ordered: false, number: nil))
                listNumber = 0
                continue
            }

            // Ordered list
            if let match = parseOrderedListItem(trimmed) {
                flushParagraph(&blocks, &currentParagraph)
                listNumber += 1
                blocks.append(.listItem(text: match, ordered: true, number: listNumber))
                continue
            }

            currentParagraph.append(trimmed)
        }

        flushParagraph(&blocks, &currentParagraph)
        return blocks
    }

    private func flushParagraph(_ blocks: inout [MarkdownBlock], _ paragraph: inout [String]) {
        if !paragraph.isEmpty {
            blocks.append(.paragraph(text: paragraph.joined(separator: " ")))
            paragraph = []
        }
    }

    private func parseOrderedListItem(_ line: String) -> String? {
        let pattern = "^\\d+\\.\\s+(.+)$"
        guard let regex = try? NSRegularExpression(pattern: pattern),
              let match = regex.firstMatch(in: line, range: NSRange(line.startIndex..., in: line)),
              let textRange = Range(match.range(at: 1), in: line) else {
            return nil
        }
        return String(line[textRange])
    }

    // MARK: - Rendering

    @ViewBuilder
    private func renderBlock(_ block: MarkdownBlock) -> some View {
        switch block {
        case .heading(let level, let text):
            renderHeading(level: level, text: text)
        case .paragraph(let text):
            renderParagraph(text)
        case .listItem(let text, let ordered, let number):
            renderListItem(text: text, ordered: ordered, number: number)
        }
    }

    @ViewBuilder
    private func renderHeading(level: Int, text: String) -> some View {
        let font: Font = switch level {
        case 1: .title2.bold()
        case 2: .title3.bold()
        default: .headline
        }

        Text(text)
            .font(font)
            .padding(.top, level == 1 ? 12 : 8)
            .padding(.bottom, 4)
    }

    @ViewBuilder
    private func renderParagraph(_ text: String) -> some View {
        Text(convertReferencesToPlainText(text))
            .font(.body)
            .padding(.vertical, 2)
    }

    @ViewBuilder
    private func renderListItem(text: String, ordered: Bool, number: Int?) -> some View {
        HStack(alignment: .top, spacing: 8) {
            if ordered, let num = number {
                Text("\(num).")
                    .font(.body)
                    .fontWeight(.semibold)
                    .frame(width: 20, alignment: .trailing)
            } else {
                Text("•")
                    .font(.body)
                    .fontWeight(.bold)
                    .frame(width: 20, alignment: .trailing)
            }
            Text(convertReferencesToPlainText(text))
                .font(.body)
        }
        .padding(.vertical, 1)
        .padding(.leading, 8)
    }

    // MARK: - Reference Conversion

    /// Convert interactive references to plain text with PMIDs.
    ///
    /// Converts `[Author, Year](doc:pmid-12345)` to `Author, Year (PMID: 12345)`.
    private func convertReferencesToPlainText(_ text: String) -> String {
        var result = text

        // Pattern for references with document ID: [Author, Year](doc:pmid-12345)
        let patternWithId = "\\[([^\\]]+)\\]\\(doc:pmid-(\\d+)\\)"
        if let regex = try? NSRegularExpression(pattern: patternWithId) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1 (PMID: $2)"
            )
        }

        // Pattern for references with generic doc ID: [Author, Year](doc:id)
        let patternGenericId = "\\[([^\\]]+)\\]\\(doc:[^)]+\\)"
        if let regex = try? NSRegularExpression(pattern: patternGenericId) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1"
            )
        }

        // Remove remaining markdown link syntax: [text](url) -> text
        let linkPattern = "\\[([^\\]]+)\\]\\([^)]+\\)"
        if let regex = try? NSRegularExpression(pattern: linkPattern) {
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                range: range,
                withTemplate: "$1"
            )
        }

        // Handle bold/italic markdown
        result = result.replacingOccurrences(of: "**", with: "")
        result = result.replacingOccurrences(of: "__", with: "")

        return result
    }

    private func normalizeLineBreaks(_ text: String) -> String {
        var result = text
        result = result.replacingOccurrences(of: "\\n", with: "\n")
        while result.contains("\n\n\n") {
            result = result.replacingOccurrences(of: "\n\n\n", with: "\n\n")
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
