// BMLibrarian Lite - Biomedical Literature Research Tool
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// Full-screen disclaimer shown on first app launch.
///
/// Explains the limitations of AI-generated medical information and
/// emphasizes the importance of consulting healthcare professionals.
struct DisclaimerView: View {
    /// Callback when user accepts the disclaimer.
    let onAccept: () -> Void

    var body: some View {
        VStack(spacing: 24) {
            Spacer()

            // App icon/branding
            VStack(spacing: 12) {
                Image(systemName: "checkmark.shield.fill")
                    .font(.system(size: 80))
                    .foregroundStyle(
                        LinearGradient(
                            colors: [.blue, .cyan],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )

                Text("Medical Fact Checker")
                    .font(.largeTitle)
                    .fontWeight(.bold)

                Text("AI-Powered Medical Literature Analysis")
                    .font(.subheadline)
                    .foregroundColor(.secondary)
            }

            Spacer()

            // Disclaimer content
            VStack(alignment: .leading, spacing: 16) {
                disclaimerHeader

                disclaimerPoints

                disclaimerFooter
            }
            .padding()
            .background(Color.orange.opacity(0.1))
            .cornerRadius(16)
            .padding(.horizontal)

            Spacer()

            // Accept button
            Button(action: onAccept) {
                Text("I Understand")
                    .font(.headline)
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color.accentColor)
                    .foregroundColor(.white)
                    .cornerRadius(12)
            }
            .padding(.horizontal)
            .padding(.bottom, 20)
        }
        #if os(iOS)
        .background(Color(uiColor: .systemBackground))
        #else
        .background(Color(nsColor: .windowBackgroundColor))
        #endif
    }

    // MARK: - Disclaimer Components

    private var disclaimerHeader: some View {
        HStack(spacing: 8) {
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.title2)
                .foregroundColor(.orange)
            Text("Important Information")
                .font(.headline)
        }
    }

    private var disclaimerPoints: some View {
        VStack(alignment: .leading, spacing: 12) {
            disclaimerPoint(
                icon: "brain.head.profile",
                title: "AI-Generated Analysis",
                text: "Reports are generated by artificial intelligence and may contain errors or omissions."
            )

            disclaimerPoint(
                icon: "stethoscope",
                title: "Not Medical Advice",
                text: "This app does not provide medical diagnosis, treatment recommendations, or professional healthcare advice."
            )

            disclaimerPoint(
                icon: "person.2.fill",
                title: "Consult Professionals",
                text: "Always discuss findings with qualified healthcare professionals before making any health decisions."
            )

            disclaimerPoint(
                icon: "exclamationmark.circle.fill",
                title: "No Self-Treatment",
                text: "Never use this app for self-diagnosis or to replace professional medical consultation."
            )

            disclaimerPoint(
                icon: "lock.shield",
                title: "Your Privacy",
                text: "Your queries are sent to LLM providers for processing. No personal health data is stored externally."
            )
        }
    }

    private func disclaimerPoint(icon: String, title: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: icon)
                .font(.title3)
                .foregroundColor(.accentColor)
                .frame(width: 28)

            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.subheadline)
                    .fontWeight(.semibold)
                Text(text)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
    }

    private var disclaimerFooter: some View {
        Text("By continuing, you acknowledge that you have read and understood these limitations.")
            .font(.caption2)
            .foregroundColor(.secondary)
            .multilineTextAlignment(.center)
            .frame(maxWidth: .infinity)
            .padding(.top, 8)
    }
}

#Preview {
    DisclaimerView(onAccept: {})
}
